#!/bin/bash

# Script to add test plans to Xcode project
# This is a workaround since we can't modify .pbxproj directly safely

echo "📋 Test Plans Setup Instructions"
echo "================================"
echo ""
echo "To add test plans to your Xcode project, follow these steps:"
echo ""
echo "1. Open Timer.xcodeproj in Xcode"
echo ""
echo "2. Go to: Product → Scheme → Edit Scheme... (Cmd+<)"
echo ""
echo "3. Select 'Test' in the left sidebar"
echo ""
echo "4. Click 'Convert to use Test Plans...'"
echo ""
echo "5. Choose one of these test plans:"
echo "   - UnitOnly (recommended for default)"
echo "   - CI"
echo "   - AllTests"
echo "   - Smoke"
echo "   - Performance"
echo "   - Regression"
echo ""
echo "6. Click 'Close'"
echo ""
echo "Available test plans in this directory:"
ls -1 *.xctestplan 2>/dev/null || echo "No test plans found"
echo ""
echo "✅ After setup, you can switch test plans in Xcode:"
echo "   Product → Scheme → Edit Scheme → Test → Test Plans"
echo ""
echo "Or use the run-tests.sh script:"
echo "   ./run-tests.sh unit"
echo "   ./run-tests.sh ci"
echo "   ./run-tests.sh all"
